package org.example.model;
// Generated Jan 27, 2023, 3:03:53 PM by Hibernate Tools 5.2.11.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="studentgradingsys"
)
public class Users  implements java.io.Serializable {
     private int id;
     private Role role;
     private String name;
     private String username;
     private String password;
    public Users() {
    }

    public Users(int id, Role role, String name, String username, String password) {
        this.id = id;
        this.role = role;
        this.name = name;
        this.username = username;
        this.password = password;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="role_id", nullable=false)
    public Role getRole() {
        return this.role;
    }

    public void setRole(Role role) {
        this.role = role;
    }

    @Column(name="name", nullable=false, length=64)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name="username", nullable=false)
    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Column(name = "password", nullable = false)
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
}


